export const VERSION = '0.1.0';
export * from './SpaceEngine';
export type { QualitySetting, QualityTier } from './quality/QualityManager';
export type { PerfSample } from './perf/PerfMonitor';
export type { ProviderFactory } from './scene/prepareEntities';
export type { PointSource, PointSourceBuffers } from './layers/PointSource';
export type { EngineApi } from './EngineApi';
export type { CameraFrame, CameraFrameResult } from './camera/CameraReference';
export type { EngineLayerState } from './layers/LayerRegistry';
export type { ObjectInView } from './scene/ObjectsInView';
export const API_VERSION = 1 as const;
