import { mkdir, writeFile } from 'node:fs/promises';
const entries: [
  string,
  string,
  string,
  number,
  number,
  string,
  string,
  string,
][] = [
  [
    'star',
    'Sun',
    '',
    695700,
    0,
    '#ffcd77',
    'sun',
    'The star at the center of our solar system. Its light takes about eight minutes to reach Earth.',
  ],
  [
    'planet',
    'Mercury',
    'star:sun',
    2439.7,
    87.969,
    '#bfb4a2',
    'mercury',
    'A small, cratered world with the most extreme daily temperature swings of any planet.',
  ],
  [
    'planet',
    'Venus',
    'star:sun',
    6051.8,
    224.701,
    '#e6c695',
    'venus_atmosphere',
    'A volcanic world wrapped in thick clouds, with a crushing carbon dioxide atmosphere.',
  ],
  [
    'planet',
    'Earth',
    'star:sun',
    6371.0084,
    365.256,
    '#78b8e8',
    'earth_daymap',
    'Our ocean world. The only place in the universe where we know life exists.',
  ],
  [
    'moon',
    'Moon',
    'planet:earth',
    1737.4,
    27.322,
    '#ccc9c3',
    'moon',
    'Earth’s companion preserves a record of billions of years of solar system history.',
  ],
  [
    'planet',
    'Mars',
    'star:sun',
    3389.5,
    686.98,
    '#d98059',
    'mars',
    'A cold desert world with giant volcanoes, ancient riverbeds, and two small moons.',
  ],
  [
    'planet',
    'Jupiter',
    'star:sun',
    69911,
    4332.59,
    '#d7b393',
    'jupiter',
    'The largest planet, with powerful storms and a system of remarkably diverse moons.',
  ],
  [
    'planet',
    'Saturn',
    'star:sun',
    58232,
    10759.22,
    '#ead5a2',
    'saturn',
    'An immense gas giant surrounded by bright rings made largely of water ice.',
  ],
  [
    'planet',
    'Uranus',
    'star:sun',
    25362,
    30688.5,
    '#9ee0e3',
    'uranus',
    'An ice giant that rolls around the Sun on its side.',
  ],
  [
    'planet',
    'Neptune',
    'star:sun',
    24622,
    60182,
    '#557fef',
    'neptune',
    'Dark, cold, and swept by supersonic winds at the edge of the planetary realm.',
  ],
  [
    'dwarf',
    'Pluto',
    'star:sun',
    1188.3,
    90560,
    '#c9b7a7',
    '',
    'A complex icy world in the Kuiper belt, explored by New Horizons in 2015.',
  ],
  [
    'dwarf',
    'Ceres',
    'star:sun',
    469.7,
    1680,
    '#b5b2aa',
    '',
    'The largest object in the asteroid belt, with bright salt deposits and a water-rich interior.',
  ],
  [
    'moon',
    'Phobos',
    'planet:mars',
    11.267,
    0.31891,
    '#a09584',
    '',
    'Mars’s inner moon is a small, irregular body orbiting close to the planet.',
  ],
  [
    'moon',
    'Deimos',
    'planet:mars',
    6.2,
    1.26244,
    '#b2a28a',
    '',
    'The smaller and more distant of Mars’s two moons.',
  ],
  [
    'moon',
    'Io',
    'planet:jupiter',
    1821.6,
    1.769,
    '#dbc978',
    '',
    'A volcanic moon heated by Jupiter’s immense tidal forces.',
  ],
  [
    'moon',
    'Europa',
    'planet:jupiter',
    1560.8,
    3.551,
    '#d6cbb0',
    '',
    'A fractured ice shell may conceal a global ocean.',
  ],
  [
    'moon',
    'Ganymede',
    'planet:jupiter',
    2634.1,
    7.155,
    '#aea899',
    '',
    'The largest moon in the solar system, with its own magnetic field.',
  ],
  [
    'moon',
    'Callisto',
    'planet:jupiter',
    2410.3,
    16.689,
    '#979186',
    '',
    'A heavily cratered world on the outskirts of Jupiter’s main moon system.',
  ],
  [
    'moon',
    'Titan',
    'planet:saturn',
    2574.73,
    15.945,
    '#d6a75e',
    '',
    'A hazy moon with methane lakes and a thick nitrogen atmosphere.',
  ],
  [
    'moon',
    'Triton',
    'planet:neptune',
    1353.4,
    5.877,
    '#cbbcc2',
    '',
    'Neptune’s largest moon orbits in the opposite direction to its planet’s rotation.',
  ],
  [
    'moon',
    'Charon',
    'dwarf:pluto',
    606,
    6.387,
    '#b0a5a1',
    '',
    'Pluto’s large companion shares a mutual, tidally locked dance.',
  ],
];
const analytic = new Set([
  'Sun',
  'Mercury',
  'Venus',
  'Earth',
  'Moon',
  'Mars',
  'Jupiter',
  'Saturn',
  'Uranus',
  'Neptune',
  'Pluto',
]);
const galilean = new Set(['Io', 'Europa', 'Ganymede', 'Callisto']);
const bodies = entries.map(
  (
    [
      kind,
      name,
      parentId,
      meanRadiusKm,
      periodDays,
      color,
      texture,
      description,
    ],
    i,
  ) => ({
    id: `${kind}:${name.toLowerCase()}`,
    kind,
    name,
    aliases:
      name === 'Earth'
        ? ['Terra', 'our planet']
        : name === 'Moon'
          ? ['Luna']
          : [],
    ...(parentId ? { parentId } : {}),
    ...(analytic.has(name) ? { astronomyBody: name } : {}),
    physical: { meanRadiusKm, ...(periodDays ? { periodDays } : {}) },
    color,
    ...(texture ? { texture } : {}),
    importance: 100 - i,
    description,
    provenance: {
      providerId:
        analytic.has(name) || galilean.has(name)
          ? 'astronomy-engine'
          : 'jpl-mean-elements',
      sourceUrl:
        analytic.has(name) || galilean.has(name)
          ? 'https://github.com/cosinekitty/astronomy'
          : 'https://ssd.jpl.nasa.gov/sats/elem/',
      method:
        analytic.has(name) || galilean.has(name)
          ? 'analytic-ephemeris'
          : 'mean-elements',
      certainty:
        analytic.has(name) || galilean.has(name) ? 'computed' : 'approximate',
    },
    tags: [],
  }),
);
await mkdir('packages/domain/data', { recursive: true });
await writeFile(
  'packages/domain/data/bodies.json',
  JSON.stringify(bodies, null, 2),
);
